#!/usr/bin/env ruby
#
# Jean-Francois Theroux <me@failshell.io>
#
# Parallel SSH executor. Only supports key-based
# authentication for now.

require 'mixlib/cli'
require 'net/ssh'
require 'peach'

module Hydra
  VERSION = '0.0.2'
  class CLI
    class Options
      include Mixlib::CLI

      option :cmd,
        :short => '-c COMMAND',
        :long => '--command COMMAND',
        :description => 'Command to execute',
        :required => true

      option :file,
        :short => '-f FILE',
        :long => '--file FILE',
        :description => 'Hosts to execute the command on',
        :required => true

      option :user,
        :short => '-u USER',
        :long => '--user USER',
        :description => 'Authenticating user',
        :required => true

    end
  end
end

# Get options
opts = Hydra::CLI::Options.new
opts.parse_options

# Read hosts
hosts = Array.new
File.open(opts.config[:file]).each_line do |l|
  hosts << l.chomp("\n")
end

# Execute command
hosts.peach do |host|
  Net::SSH.start(host, opts.config[:user]) do |ssh|
    o = ssh.exec!(opts.config[:cmd])
    puts host
    puts '---------------------'
    puts o
    puts ''
  end
end
